### ISSUE TITLE
Allow for automatic "Yes" opt-in to telemetry

### ISSUE THREAD

**Issue by nathanchase** [nuxt/telemetry#16]
Currently, during a build, Nuxt asks "Are you interested in participation? (Y/n)" and requires a user response. 

This is something that needs to be able to be automated for use inside Docker deployments, continuous integrations, cloud instance deployments, or otherwise unattended server builds/starts of Nuxt.

I recommend an `accept` boolean to facilitate telemetry opt-in AND automatically proceed with a build.

**Comment by mkriesten** [comment]
I second that. I was only able to get my application running on AWS through my pipeline by disabling telemetry in nuxt.config.

`module.exports = {  
   telemetry: false,
}
`

Also, my application was unable to even run. I assume, because nuxt-telemetry was unable to connect. I saw error messages in CloudWatch that '/home/$user/.nuxtrc cannot be opened. Also, my pipeline said the following, because my firewall did not allow connection:

[error] [@nuxt/telemetry] Error sending sent to `https://telemetry.nuxtjs.com` (26 ms)
request to https://telemetry.nuxtjs.com/ failed, reason: connect ECONNREFUSED

**Comment by nathanchase** [comment]
@pi0 I see there's an `options.consent` boolean under `TelemetryOptions`, but I think it's not exposed at the nuxt.config level? So just a refactor perhaps to allow something like:

```js
export default {
  telemetry: {
     enabled: true,
     consent: true
  }
}
```

**Comment by pi0** [comment]
Hi. Better CI detection is implemented with [v1.1.0](https://github.com/nuxt/telemetry/releases/tag/v1.1.0) so prompt will be auto skipped on CI environments. Also using `nuxt telemetry enable` sets `consent` value too now. You can recreate `yarn.lock` or use `yarn upgrade nuxt` to get the fixes.

@nathanchase If you prefer `nuxt.config` instead of `.nuxtrc`, it is still possible just value of `consent` should be `1` (will be increased if telemetry terms changes). Technically `.nuxtrc` (both global and per-project) provide defaults for `nuxt.config` (see https://github.com/nuxt/nuxt.js/pull/7430)

@mkriesten (unrelated point) If you see telemetry log without manually enabling DEBUG, it is likely you are using some outdated dependencies (including `consola`). I would recommend recreating lock-file.

**Comment by nathanchase** [comment]
Sounds good. Thanks, @pi0!

**Comment by pi0** [comment]
Update: with latest release `telemetry: true` support also added to skip `consent` (as a shortcut to https://github.com/nuxt/telemetry/issues/16#issuecomment-647014318)
